/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
      extend: {
          colors: {
              "primary-fixed": "#a5c1ff",
              "on-secondary": "#5f00a4",
              "secondary-fixed": "#f0dbff",
              "surface": "#070d1f",
              "inverse-primary": "#005bc4",
              "surface-dim": "#070d1f",
              "outline": "#68749b",
              "secondary": "#ddb7ff",
              "outline-variant": "#3b476b",
              "secondary-fixed-dim": "#e7c9ff",
              "surface-variant": "#182446",
              "on-surface-variant": "#9eaad3",
              "on-tertiary": "#7c0953",
              "primary-dim": "#699cff",
              "on-secondary-fixed": "#5e00a2",
              "on-primary-fixed": "#002659",
              "tertiary": "#ffafd3",
              "surface-bright": "#1c2a51",
              "on-primary-fixed-variant": "#004292",
              "tertiary-fixed-dim": "#ff81c1",
              "background": "#070d1f",
              "surface-container-high": "#131e3c",
              "error-dim": "#c8475d",
              "primary": "#699cff",
              "on-error": "#490013",
              "on-tertiary-fixed": "#46002c",
              "surface-container-highest": "#182446",
              "on-tertiary-container": "#6e0048",
              "secondary-container": "#3a0068",
              "inverse-on-surface": "#4f5469",
              "surface-container": "#0f1832",
              "tertiary-dim": "#f271b5",
              "on-secondary-fixed-variant": "#8126cf",
              "primary-container": "#4388fd",
              "surface-container-lowest": "#000000",
              "on-error-container": "#ff97a3",
              "on-surface": "#dfe4ff",
              "inverse-surface": "#faf8ff",
              "on-tertiary-fixed-variant": "#7b0852",
              "on-primary": "#001e4a",
              "error-container": "#8a1632",
              "secondary-dim": "#9c48ea",
              "error": "#fd6f85",
              "on-secondary-container": "#c589ff"
          },
          fontFamily: {
              "headline": ["Manrope"],
              "display": ["Manrope"],
              "body": ["Manrope"],
              "label": ["Inter"]
          }
      },
  },
  plugins: [],
}
