const API_URL = "https://blog-app-zgxk.onrender.com";

// Modal Elements
const createModal = document.getElementById("createModal");
const titleInput = document.getElementById("title");
const contentInput = document.getElementById("content");

function openModal() {
  createModal.classList.remove("hidden");
  createModal.classList.add("flex");
}

function closeModal() {
  createModal.classList.add("hidden");
  createModal.classList.remove("flex");
}

async function createBlog() {
  const title = titleInput.value;
  const content = contentInput.value;

  if(!title || !content) {
    alert("Please fill in both fields");
    return;
  }

  await fetch(API_URL + "/posts", {
    method:"POST",
    headers: { "Content-Type" : "application/json" },
    body: JSON.stringify({ title: title, content: content })
  });

  titleInput.value = "";
  contentInput.value = "";
  closeModal();

  loadBlogs();
}

let allBlogs = [];

async function loadBlogs() {
  try {
    const res = await fetch(API_URL + "/posts");
    const blogs = await res.json();
    allBlogs = blogs;
    
    let html = "";
    
    // We'll use the awesome high-end CSS generated by Stitch for each card.
    blogs.forEach((b, index) => {
      // Toggle sizes or styles just to make the grid dynamic
      const isFeatured = index % 4 === 0;
      const aspectClass = isFeatured ? 'xl:row-span-2 md:col-span-2' : '';
      const fallbackImage = `https://picsum.photos/seed/${b._id}/800/600`;
      
      html += `
      <article class="group relative overflow-hidden rounded-[1.5rem] glass-card ghost-border flex flex-col h-full ${aspectClass}">
        <div class="aspect-video xl:aspect-auto relative overflow-hidden flex-shrink-0" style="min-height: 200px;">
          <img alt="cover" class="absolute inset-0 w-full h-full object-cover transition-transform duration-700 group-hover:scale-105 opacity-80" src="${fallbackImage}"/>
          <div class="absolute inset-0 bg-gradient-to-t from-[#070d1f] via-[#070d1f]/40 to-transparent"></div>
          <div class="absolute inset-0 bg-gradient-to-t from-surface-container-high/90 to-transparent"></div>
        </div>
        <div class="${isFeatured ? 'absolute bottom-0' : ''} p-6 flex flex-col items-start gap-4 z-10 w-full">
          <h3 class="${isFeatured ? 'text-3xl md:text-4xl leading-tight' : 'text-xl leading-tight'} font-headline font-bold tracking-tight text-white drop-shadow-md">${b.title}</h3>
          
          <p class="text-on-surface-variant text-sm line-clamp-3 font-light leading-relaxed truncate-multiline drop-shadow-sm">${b.content}</p>
          
          <div class="flex items-center gap-6 mt-2 w-full justify-between">
            <div class="flex items-center gap-2">
              <span class="material-symbols-outlined text-sm text-primary">schedule</span>
              <span class="font-label text-xs text-on-surface-variant">${new Date(b.createdAt).toLocaleDateString()}</span>
            </div>
            <div class="flex gap-2">
              <button onclick="editBlog('${b._id}')" class="text-[#699cff] hover:text-white transition-colors bg-white/5 p-2 rounded-full backdrop-blur-md">
                <span class="material-symbols-outlined text-sm">edit</span>
              </button>
              <button onclick="deleteBlog('${b._id}')" class="text-[#fd6f85] hover:text-white transition-colors bg-white/5 p-2 rounded-full backdrop-blur-md">
                <span class="material-symbols-outlined text-sm">delete</span>
              </button>
            </div>
          </div>
        </div>
      </article>
      `;
    });
    
    document.getElementById("blogs").innerHTML = html;
    
    // Update Storage Bar logic as a rough estimate based on number of posts
    const maxPosts = 100;
    const postCount = blogs.length;
    const percentage = Math.min((postCount / maxPosts) * 100, 100).toFixed(0);
    const storageBar = document.getElementById("storageBar");
    const storageText = document.getElementById("storageText");
    if(storageBar && storageText) {
      storageBar.style.width = percentage + "%";
      storageText.innerText = `${postCount} Posts Created`;
    }

  } catch (error) {
    console.error("Error loading blogs", error);
  }
}

async function deleteBlog(id) {
  if(!confirm("Are you sure you want to delete this exquisite artifact?")) return;
  await fetch(API_URL + "/posts/" + id, { method:"DELETE" });
  loadBlogs();
}

// Edit Modal Elements
const editModal = document.getElementById("editModal");
const editIdInput = document.getElementById("edit-id");
const editTitleInput = document.getElementById("edit-title");
const editContentInput = document.getElementById("edit-content");

function closeEditModal() {
  editModal.classList.add("hidden");
  editModal.classList.remove("flex");
}

function editBlog(id) {
  const blog = allBlogs.find(b => b._id === id);
  if(!blog) return;

  editIdInput.value = blog._id;
  editTitleInput.value = blog.title;
  editContentInput.value = blog.content;

  editModal.classList.remove("hidden");
  editModal.classList.add("flex");
}

async function submitEditBlog() {
  const id = editIdInput.value;
  const newTitle = editTitleInput.value;
  const newContent = editContentInput.value;

  if(!newTitle || !newContent) {
    alert("Please fill in both fields");
    return;
  }

  await fetch(API_URL + "/posts/" + id, {
    method:"PUT",
    headers:{ "Content-Type":"application/json" },
    body: JSON.stringify({ title: newTitle, content: newContent })
  });

  closeEditModal();
  loadBlogs();
}

// Navigation Handlers
function showFeatureAlert(featureName) {
  alert(`The ${featureName} feature is coming in the next update! Let me know if you want me to build it!`);
}

function showSection(sectionId) {
  if(sectionId === 'feed') {
    window.scrollTo({ top: 0, behavior: 'smooth' });
    loadBlogs();
  }
}

window.onload = loadBlogs;